### ISSUE TITLE
Missing Data Strategy

### ISSUE THREAD

**Issue by hoffm386** [learn-co-curriculum/dsc-pandas-data-cleaning-lab#1]
Flagged by @aspratle 

More clarity needed for the strategy for dealing with missing publishers. The tests assume that rows with missing publishers should be dropped. Can we update the tests to accommodate a different imputation strategy? Or should we make it clearer that students don't have a choice of which strategy to use?

**Comment by Cheffrey2000** [comment]
The solution for dealing with missing publishers has been updated with the following commit: [a192bd6](https://github.com/learn-co-curriculum/dsc-pandas-data-cleaning-lab/commit/a192bd6d21223ee6e38172236143f125f6a73d7b)
